version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    environment:
      - SA_PASSWORD=yourpassword
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  webshop:
    build: .
    container_name: webshop-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=WebShopDb;User Id=sa;Password=yourpassword;MultipleActiveResultSets=true
    ports:
      - "8080:80"
    depends_on:
      - db
